### PR TITLE
Refactoring GRBL-Plotter with C#6 features

### PR DESCRIPTION
**Pull request by RasyidUFA**
I refactored some code, and it's checked no warning appear

### CODE REVIEW

**Comment by RasyidUFA** [comment]
It seems that I accidentally includes #43 Commit.

**Comment by svenhb** [comment]
I don't see the advantage to replace my "Ifs" by "switch", which needs 3 lines instead of 1 line...

**Comment by rasyidf** [comment]
it's increase clarity. i guess

**Comment by svenhb** [comment]
Yes there is a chance. 
1st I need to follow all changings, then I need to figure out how to select files for merging.
What is gitignore good for? I upload all files manually.
What are the changings in MainForm.resx did you replace images?
Why no default value setter?

**Comment by svenhb** [comment]
I took over usufull changes manually.
Thanks for your work.

**Pull request closed without merging**
